version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: keep2anytype
    main: .
    binary: keep2anytype
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    ids: [keep2anytype]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

release:
  mode: replace

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
